import logging
from io import BytesIO
from typing import Dict, Optional
from datetime import datetime

from django.conf import settings
from django.core.mail import send_mail, EmailMessage
from django.template.loader import render_to_string

logger = logging.getLogger(__name__)


class ExportManager:
    def __init__(self):
        self._reportlab_available = True
        try:
            from reportlab.lib.pagesizes import letter, A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
            from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
            from reportlab.lib.colors import HexColor, black, white
        except ImportError:
            self._reportlab_available = False
            logger.warning("ReportLab not available for PDF export")
    
    def export_to_pdf(self, analysis_result: Dict, document_title: str) -> BytesIO:
        if not self._reportlab_available:
            raise ImportError("ReportLab is required for PDF export. Install it with: pip install reportlab")
        
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, HRFlowable
        from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
        from reportlab.lib.colors import HexColor
        
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=0.6*inch,
            leftMargin=0.6*inch,
            topMargin=0.6*inch,
            bottomMargin=0.6*inch
        )
        
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=22,
            textColor=HexColor('#6366f1'),
            spaceAfter=5,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        subtitle_style = ParagraphStyle(
            'Subtitle',
            parent=styles['Normal'],
            fontSize=12,
            textColor=HexColor('#888888'),
            spaceAfter=20,
            alignment=TA_CENTER
        )
        
        section_header_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=HexColor('#ffffff'),
            spaceBefore=15,
            spaceAfter=8,
            fontName='Helvetica-Bold',
            backColor=HexColor('#6366f1'),
            borderPadding=(8, 10, 8, 10),
            leftIndent=-5,
            rightIndent=-5
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=13,
            textColor=HexColor('#ec4899'),
            spaceBefore=15,
            spaceAfter=8,
            fontName='Helvetica-Bold'
        )
        
        subheading_style = ParagraphStyle(
            'SubHeading',
            parent=styles['Heading3'],
            fontSize=11,
            textColor=HexColor('#8b5cf6'),
            spaceBefore=10,
            spaceAfter=5,
            fontName='Helvetica-Bold'
        )
        
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            alignment=TA_JUSTIFY,
            spaceAfter=8
        )
        
        keyword_style = ParagraphStyle(
            'KeywordStyle',
            parent=styles['Normal'],
            fontSize=9,
            textColor=HexColor('#6366f1'),
            spaceAfter=4
        )
        
        badge_style = ParagraphStyle(
            'Badge',
            parent=styles['Normal'],
            fontSize=9,
            textColor=HexColor('#065f46'),
            backColor=HexColor('#d1fae5'),
            borderPadding=3,
            spaceAfter=3,
            spaceBefore=3
        )
        
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=HexColor('#999999'),
            alignment=TA_CENTER
        )
        
        story = []
        
        story.append(Paragraph("Research Paper Analysis Report", title_style))
        story.append(Paragraph(f"Generated by PaperAIzer | {datetime.now().strftime('%B %d, %Y at %H:%M')}", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=2, color=HexColor('#6366f1'), spaceAfter=20))
        
        story.append(Paragraph("Document Information", section_header_style))
        
        meta_data = [
            ["<b>Title:</b>", document_title],
            ["<b>Analysis Date:</b>", analysis_result.get('created_at', datetime.now().strftime('%Y-%m-%d %H:%M'))],
        ]
        if analysis_result.get('authors'):
            meta_data.append(["<b>Authors:</b>", ", ".join(analysis_result['authors'][:5])])
        if analysis_result.get('publication_year'):
            meta_data.append(["<b>Publication Year:</b>", str(analysis_result['publication_year'])])
        if analysis_result.get('word_count'):
            meta_data.append(["<b>Word Count:</b>", f"{analysis_result['word_count']:,}"])
        
        for label, value in meta_data:
            story.append(Paragraph(f"{label} {value}", body_style))
        
        if analysis_result.get('abstract'):
            story.append(Paragraph("Abstract", section_header_style))
            story.append(Paragraph(analysis_result['abstract'], body_style))
        
        if analysis_result.get('summary'):
            story.append(Paragraph("Summary", section_header_style))
            story.append(Paragraph(analysis_result['summary'], body_style))
        
        if analysis_result.get('keywords'):
            story.append(Paragraph("Keywords", section_header_style))
            story.append(Spacer(1, 5))
            keywords_html = "  ".join([f"<b>{kw}</b>" for kw in analysis_result['keywords']])
            story.append(Paragraph(keywords_html, keyword_style))
        
        if analysis_result.get('methodology'):
            story.append(Paragraph("Methodology", section_header_style))
            for method in analysis_result['methodology']:
                story.append(Paragraph(f"• {method}", body_style))
        
        if analysis_result.get('technologies'):
            story.append(Paragraph("Technologies & Tools", section_header_style))
            story.append(Spacer(1, 5))
            techs_html = "  ".join([f"<b>{t}</b>" for t in analysis_result['technologies']])
            story.append(Paragraph(techs_html, keyword_style))
        
        if analysis_result.get('extras', {}).get('method_approach'):
            story.append(Paragraph("Methodology & Approach", section_header_style))
            story.append(Paragraph(analysis_result['extras']['method_approach'], body_style))
        
        if analysis_result.get('goal'):
            story.append(Paragraph("Research Goal", heading_style))
            story.append(Paragraph(analysis_result['goal'], body_style))
        
        if analysis_result.get('impact'):
            story.append(Paragraph("Research Impact", heading_style))
            story.append(Paragraph(analysis_result['impact'], body_style))
        
        if analysis_result.get('conclusion'):
            story.append(Paragraph("Conclusion", section_header_style))
            story.append(Paragraph(analysis_result['conclusion'], body_style))
        
        if analysis_result.get('research_gaps'):
            story.append(Paragraph("Research Gaps & Future Work", section_header_style))
            for gap in analysis_result['research_gaps']:
                story.append(Paragraph(f"• {gap[:500]}", body_style))
        
        extras = analysis_result.get('extras', {})
        dataset_names = analysis_result.get('dataset_names', [])
        dataset_size = extras.get('dataset_size')
        dataset_source = extras.get('dataset_source')
        if dataset_names or dataset_size or dataset_source:
            story.append(Paragraph("Dataset Information", section_header_style))
            for name in dataset_names[:10]:
                story.append(Paragraph(f"• {name}", body_style))
            if dataset_size:
                story.append(Paragraph(f"<b>Size:</b> {dataset_size}", body_style))
            if dataset_source:
                story.append(Paragraph(f"<b>Source:</b> {dataset_source}", body_style))
        
        visual_assets = extras.get('visual_assets', {})
        if visual_assets:
            counts = visual_assets.get('counts', {})
            if counts.get('figures') or counts.get('tables') or counts.get('charts'):
                story.append(Paragraph("Visual Elements", heading_style))
                if counts.get('figures'):
                    story.append(Paragraph(f"• Figures: {counts.get('figures')}", body_style))
                if counts.get('tables'):
                    story.append(Paragraph(f"• Tables: {counts.get('tables')}", body_style))
                if counts.get('charts'):
                    story.append(Paragraph(f"• Charts/Diagrams: {counts.get('charts')}", body_style))
        
        plagiarism = extras.get('plagiarism', {})
        if plagiarism and plagiarism.get('similarity_percent') is not None:
            story.append(Paragraph("Plagiarism Check", heading_style))
            sim = plagiarism.get('similarity_percent', 0)
            risk = plagiarism.get('risk_level', 'N/A')
            story.append(Paragraph(f"Similarity Score: <b>{sim}%</b> | Risk Level: <b>{risk}</b>", body_style))
        
        if analysis_result.get('extracted_links'):
            story.append(PageBreak())
            story.append(Paragraph("Extracted Links", section_header_style))
            for link in analysis_result['extracted_links'][:20]:
                story.append(Paragraph(f"• <link href='{link}'>{link}</link>", body_style))
        
        if analysis_result.get('references'):
            story.append(Paragraph("References", section_header_style))
            for ref in analysis_result['references'][:20]:
                if isinstance(ref, dict):
                    ref_text = f"{ref.get('authors', 'Unknown')} ({ref.get('year', 'n.d')}) - {ref.get('title', 'Untitled')}"
                else:
                    ref_text = str(ref)[:200]
                story.append(Paragraph(f"• {ref_text}", body_style))
        
        if analysis_result.get('word_count') or analysis_result.get('unique_words'):
            story.append(Paragraph("Document Statistics", heading_style))
            story.append(Paragraph(f"• Word Count: {analysis_result.get('word_count', 0):,}", body_style))
            story.append(Paragraph(f"• Unique Words: {analysis_result.get('unique_words', 0):,}", body_style))
            story.append(Paragraph(f"• Characters: {analysis_result.get('character_count', 0):,}", body_style))
            story.append(Paragraph(f"• Keywords Found: {len(analysis_result.get('keywords', [])):,}", body_style))
            story.append(Paragraph(f"• References: {len(analysis_result.get('references', [])):,}", body_style))
        
        story.append(Spacer(1, 30))
        story.append(HRFlowable(width="100%", thickness=1, color=HexColor('#e2e8f0'), spaceAfter=10))
        story.append(Paragraph("— Generated by PaperAIzer —", footer_style))
        
        doc.build(story)
        
        buffer.seek(0)
        return buffer
    
    def export_to_text(self, analysis_result: Dict, document_title: str) -> str:
        lines = []
        
        lines.append("=" * 80)
        lines.append("       RESEARCH PAPER ANALYSIS REPORT")
        lines.append("=" * 80)
        lines.append(f"Generated by PaperAIzer | {datetime.now().strftime('%B %d, %Y at %H:%M')}")
        lines.append("=" * 80)
        lines.append("")
        
        lines.append(">>> DOCUMENT INFORMATION <<<")
        lines.append("-" * 40)
        lines.append(f"Title: {document_title}")
        lines.append(f"Analysis Date: {analysis_result.get('created_at', datetime.now().strftime('%Y-%m-%d %H:%M'))}")
        if analysis_result.get('authors'):
            lines.append(f"Authors: {', '.join(analysis_result['authors'][:5])}")
        if analysis_result.get('publication_year'):
            lines.append(f"Publication Year: {analysis_result['publication_year']}")
        if analysis_result.get('word_count'):
            lines.append(f"Word Count: {analysis_result['word_count']:,}")
        lines.append("")
        
        if analysis_result.get('abstract'):
            lines.append(">>> ABSTRACT <<<")
            lines.append("-" * 40)
            lines.append(analysis_result['abstract'])
            lines.append("")
        
        if analysis_result.get('summary'):
            lines.append(">>> SUMMARY <<<")
            lines.append("-" * 40)
            lines.append(analysis_result['summary'])
            lines.append("")
        
        if analysis_result.get('keywords'):
            lines.append(">>> KEYWORDS <<<")
            lines.append("-" * 40)
            lines.append(" | ".join(analysis_result['keywords']))
            lines.append("")
        
        if analysis_result.get('methodology'):
            lines.append(">>> METHODOLOGY <<<")
            lines.append("-" * 40)
            for method in analysis_result['methodology']:
                lines.append(f"  - {method}")
            lines.append("")
        
        if analysis_result.get('technologies'):
            lines.append(">>> TECHNOLOGIES & TOOLS <<<")
            lines.append("-" * 40)
            lines.append(" | ".join(analysis_result['technologies']))
            lines.append("")
        
        extras = analysis_result.get('extras', {})
        if extras.get('method_approach'):
            lines.append(">>> METHODOLOGY & APPROACH <<<")
            lines.append("-" * 40)
            lines.append(extras['method_approach'])
            lines.append("")
        
        if analysis_result.get('goal'):
            lines.append(">>> RESEARCH GOAL <<<")
            lines.append("-" * 40)
            lines.append(analysis_result['goal'])
            lines.append("")
        
        if analysis_result.get('impact'):
            lines.append(">>> RESEARCH IMPACT <<<")
            lines.append("-" * 40)
            lines.append(analysis_result['impact'])
            lines.append("")
        
        if analysis_result.get('conclusion'):
            lines.append(">>> CONCLUSION <<<")
            lines.append("-" * 40)
            lines.append(analysis_result['conclusion'])
            lines.append("")
        
        if analysis_result.get('research_gaps'):
            lines.append(">>> RESEARCH GAPS & FUTURE WORK <<<")
            lines.append("-" * 40)
            for gap in analysis_result['research_gaps']:
                lines.append(f"  - {gap[:500]}")
            lines.append("")
        
        dataset_names = analysis_result.get('dataset_names', [])
        dataset_size = extras.get('dataset_size')
        dataset_source = extras.get('dataset_source')
        if dataset_names or dataset_size or dataset_source:
            lines.append(">>> DATASET INFORMATION <<<")
            lines.append("-" * 40)
            for name in dataset_names[:10]:
                lines.append(f"  - {name}")
            if dataset_size:
                lines.append(f"  Size: {dataset_size}")
            if dataset_source:
                lines.append(f"  Source: {dataset_source}")
            lines.append("")
        
        visual_assets = extras.get('visual_assets', {})
        if visual_assets:
            counts = visual_assets.get('counts', {})
            if counts.get('figures') or counts.get('tables') or counts.get('charts'):
                lines.append(">>> VISUAL ELEMENTS <<<")
                lines.append("-" * 40)
                if counts.get('figures'):
                    lines.append(f"  - Figures: {counts.get('figures')}")
                if counts.get('tables'):
                    lines.append(f"  - Tables: {counts.get('tables')}")
                if counts.get('charts'):
                    lines.append(f"  - Charts/Diagrams: {counts.get('charts')}")
                lines.append("")
        
        plagiarism = extras.get('plagiarism', {})
        if plagiarism and plagiarism.get('similarity_percent') is not None:
            lines.append(">>> PLAGIARISM CHECK <<<")
            lines.append("-" * 40)
            sim = plagiarism.get('similarity_percent', 0)
            risk = plagiarism.get('risk_level', 'N/A')
            lines.append(f"Similarity Score: {sim}%")
            lines.append(f"Risk Level: {risk}")
            lines.append("")
        
        if analysis_result.get('extracted_links'):
            lines.append(">>> EXTRACTED LINKS <<<")
            lines.append("-" * 40)
            for link in analysis_result['extracted_links'][:20]:
                lines.append(f"  - {link}")
            lines.append("")
        
        if analysis_result.get('references'):
            lines.append(">>> REFERENCES <<<")
            lines.append("-" * 40)
            for i, ref in enumerate(analysis_result['references'][:20], 1):
                if isinstance(ref, dict):
                    ref_text = f"{ref.get('authors', 'Unknown')} ({ref.get('year', 'n.d')}) - {ref.get('title', 'Untitled')}"
                else:
                    ref_text = str(ref)[:200]
                lines.append(f"  {i}. {ref_text}")
            lines.append("")
        
        lines.append(">>> DOCUMENT STATISTICS <<<")
        lines.append("-" * 40)
        lines.append(f"  Word Count: {analysis_result.get('word_count', 0):,}")
        lines.append(f"  Unique Words: {analysis_result.get('unique_words', 0):,}")
        lines.append(f"  Characters: {analysis_result.get('character_count', 0):,}")
        lines.append(f"  Keywords Found: {len(analysis_result.get('keywords', [])):,}")
        lines.append(f"  References: {len(analysis_result.get('references', [])):,}")
        lines.append("")
        
        lines.append("=" * 80)
        lines.append("           Generated by PaperAIzer")
        lines.append("=" * 80)
        
        return "\n".join(lines)
    
    def send_email_report(self, email: str, analysis_result: Dict, document_title: str, export_format: str = 'pdf') -> bool:
        try:
            subject = f"Research Paper Analysis Report: {document_title[:50]}"
            
            message_text = f"""
Research Paper Analysis Report
==============================

Document: {document_title}
Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}

Summary:
{analysis_result.get('summary', 'N/A')[:500]}

Keywords: {', '.join(analysis_result.get('keywords', [])[:10])}

Methodology: {', '.join(analysis_result.get('methodology', []))}

This is an automated report from PaperAIzer.
"""
            
            # Create EmailMessage to support attachments
            email_msg = EmailMessage(
                subject=subject,
                body=message_text,
                from_email=settings.DEFAULT_FROM_EMAIL,
                to=[email]
            )
            
            # Generate and attach the report file
            if export_format == 'pdf':
                pdf_buffer = self.export_to_pdf(analysis_result, document_title)
                filename = f"analysis_{document_title[:30].replace(' ', '_')}.pdf"
                email_msg.attach(filename, pdf_buffer.read(), 'application/pdf')
            else:
                text_content = self.export_to_text(analysis_result, document_title)
                filename = f"analysis_{document_title[:30].replace(' ', '_')}.txt"
                email_msg.attach(filename, text_content, 'text/plain')
            
            email_msg.send(fail_silently=False)
            logger.info(f"Email report sent successfully to {email}")
            return True
            
        except Exception as e:
            logger.error(f"Error sending email: {e}")
            return False


export_manager = ExportManager()
