# Generated by Django 5.1.15 on 2026-03-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('pdf', 'PDF File'), ('text', 'Raw Text'), ('url', 'URL')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('methodology', models.JSONField(default=list)),
                ('technologies', models.JSONField(default=list)),
                ('goal', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('publication_year', models.CharField(blank=True, max_length=10)),
                ('extracted_links', models.JSONField(default=list)),
                ('dataset_names', models.JSONField(default=list)),
                ('dataset_links', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('authors', models.JSONField(default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('unique_words', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analyzer.document')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
            },
        ),
        migrations.CreateModel(
            name='PlagiarismCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0)),
                ('matched_sources', models.JSONField(default=list)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_checks', to='analyzer.document')),
            ],
            options={
                'verbose_name': 'Plagiarism Check',
                'verbose_name_plural': 'Plagiarism Checks',
            },
        ),
    ]
