# Generated by Django 5.1.15 on 2026-03-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='extras',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
