# Generated by Django 6.0.3 on 2026-04-05 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_document_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('inaccurate', 'Inaccurate'), ('somewhat', 'Somewhat Accurate'), ('accurate', 'Accurate'), ('very-accurate', 'Very Accurate')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='analyzer.document')),
            ],
            options={
                'verbose_name': 'Analysis Feedback',
                'verbose_name_plural': 'Analysis Feedbacks',
            },
        ),
    ]
