# Generated by Django 6.0.3 on 2026-04-07 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_analysisfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(blank=True, help_text='Text input for comparison (when not comparing two documents)')),
                ('similarity_score', models.FloatField(default=0.0)),
                ('comparison_data', models.JSONField(default=dict, help_text='Detailed comparison results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_first', to='analyzer.document')),
                ('document2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_second', to='analyzer.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comparison Result',
                'verbose_name_plural': 'Comparison Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
