# Generated by Django 6.0.3 on 2026-04-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_alter_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='model_used',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
