# Generated by Django 6.0.3 on 2026-04-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_add_model_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='character_count',
            field=models.IntegerField(default=0),
        ),
    ]
