# Generated by Django 4.2.30 on 2026-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_add_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='publication_year',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
