# Generated by Django 4.2.30 on 2026-04-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_alter_analysisresult_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='input_type',
            field=models.CharField(choices=[('pdf', 'PDF File'), ('text', 'Raw Text'), ('url', 'URL'), ('image', 'Image')], max_length=10),
        ),
    ]
